### ISSUE TITLE
Unable to clone repos that redirect from one host to another.

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/vcsstore#12]
It seems `vcsstore` doesn't like it when imports have dots, aside from the one in the host.

For example, consider the valid git remote `https://azul3d.org/audio.v1`. Doing `git clone` on it works as expected, since it's a valid git remote:

```bash
Downloads $ git clone https://azul3d.org/audio.v1
Cloning into 'audio.v1'...
remote: Counting objects: 104, done.
remote: Total 104 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (104/104), 29.80 KiB | 0 bytes/s, done.
Resolving deltas: 100% (63/63), done.
Checking connectivity... done.
Downloads $ 
```

However, vcsstore returns 500 (note, I was using `vcsclient`, but this is the underlying call it produced):

```bash
~ $ curl -X POST -i "http://localhost:9090/git/https/azul3d.org/audio.v1"
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache, max-age=0
Content-Type: text/plain; charset=utf-8
Date: Fri, 21 Nov 2014 07:42:59 GMT
Content-Length: 1


~ $ 
```

Based on a similar change in 83e3a0cb1bc93cf4897b70e6214d3f5b8da287a9, I'm guessing it has to do with how the routes are setup.

**Comment by dmitshur** [comment]
Since the `libgit2/git2go`-based `git` backend has been replaced with a `go-git`-backed one, I think this is no longer relevant. Closing.
