### ISSUE TITLE
`mux` repository doesn't exist

### ISSUE THREAD

**Issue by corebreaker** [sourcegraph/vcsstore#41]
Package `_github.com/sourcegraph/mux_` or `_sourcegraph.com/sourcegraph/mux_` can't be imported therefore this repository can't be built. The cause is that [https://github.com/sourcegraph/mux](https://github.com/sourcegraph/mux) gets a 404 HTTP code.

**Comment by emidoots** [comment]
Hi @corebreaker, thanks for the bug report!

We're not using vcsstore currently, so fixing this is low priority for us.

As a workaround, there is a copy of that package in the vendor folder which could be copied into your own projects vendor folder: https://github.com/sourcegraph/vcsstore/tree/master/Godeps/_workspace/src/github.com/sourcegraph/mux

The real fix here would be to publish that to some repository or, even better, switch this project to just using github.com/gorilla/mux (I'm not aware of what changes were made off the top of my head / if we relied on any specific modification).

Glad to accept any PR for this.

**Comment by corebreaker** [comment]
OK, i'll do that.

Thank you for the answer.

Regards.
